### PR TITLE
Uosc menu

### PR DESCRIPTION
**Pull request by cvzi**

### CODE REVIEW

**Comment by cvzi** [comment]
@NaiveInvestigator Here is a first try, can you please test it.

The script file is here: 
https://github.com/cvzi/mpv-youtube-download/blob/uosc-menu/youtube-download.lua
And here is explained how you add it:
https://github.com/cvzi/mpv-youtube-download/tree/uosc-menu#uosc-menu-integration

**Comment by NaiveInvestigator** [comment]
I tested this and I get this error:

```
[youtube_download] x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
[youtube_download] spelling of the name, or if a path was included, verify that the path is correct and try again.
[youtube_download] At line:1 char:25
[youtube_download] + mkdir D:\Program Files (x86)\mpv\portable_config/./ytdl/download
[youtube_download] +                         ~~~
[youtube_download]     + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
[youtube_download]     + FullyQualifiedErrorId : CommandNotFoundException
[youtube_download]
[youtube_download] Failed to create youtube-download save directory D:\Program Files (x86)\mpv\portable_config/./ytdl/download. Error: unknow
```
I think it is because I have a space in my path. Doing `mkdir "D:\Program Files (x86)\mpv\portable_config/./ytdl/download"` might fix the issue

Edit: Also I wanted to be sure, is there any option to download both the video file and audio file seperately and then stitch them up using ffmpeg like how [yt-dlp does](https://github.com/yt-dlp/yt-dlp#strongly-recommended). The reason for doing this is because for higher quality vids youtube usually doesn't include the audio and vice versa.

Edit - 2: Also would like to mention that the `Program Files (x86)` in the error log doesn't need admin perms, it just a folder named that so no there is no permission issues regarding that.

**Comment by cvzi** [comment]
The error should be fixed now

It just uses yt-dlp to download, so it should be exactly the same as when you use yt-dlp in a terminal

**Comment by NaiveInvestigator** [comment]
Works perfectly! I tried changing the formats, and resolutions and it handled them like a champ!

**Comment by cvzi** [comment]
I'll leave it like this then. 

Probably won't use it myself, so please just inform me if something can be improved or if the uosc-scripts changes something and it needs adapting.

**Pull request merged**
